### DISCUSSION TITLE
How to download 'latest' version programatically

### DISCUSSION THREAD

**Discussion by rungitringit** [jgraph/drawio-desktop#1450] [Q&A]
Hello,
I'd like to install this app as a part of a Linux SOE I'm building.  I wish to use a native package (deb and rpm) but as there's no repository available, how can I ensure the systems I manage always have the latest version?

Github doesn't provide a 'latest' version tag and while I can see there's a "latest-linux.yml" file available, it only seems to be downloadable from the specific version URL of the release.  I won't know these version numbers in advance.

So, how can I programmatically ensure that the latest version of the package is always sourced from here please?

Thank you!

**Comment by davidjgraph** [comment]
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

e.g. https://github.com/jgraph/drawio-desktop/releases/latest

**Reply by rungitringit** [reply]
Thanks @davidjgraph I didn't realise Github had added that!  Awesome that makes life easy for many sources too.

**Reply by rungitringit** [reply]
Thanks for the link @davidjgraph but I'm afraid this has not been resolved.

I'd love to be able to download a fixed URL for a specific file like: https://github.com/jgraph/drawio-desktop/releases/latest/drawio-amd64-latest.deb or failing that, at least be able to get https://github.com/jgraph/drawio-desktop/releases/latest/latest-linux.yml .

Unfortunately the link you provided, https://github.com/jgraph/drawio-desktop/releases/latest is redirected to a HTML page which contains the links I need.  While someone could write some python to parse that, it's beyond my time/ability for now.

_EDITS: Clarified and fixed deb reference_

**Reply by davidjgraph** [reply]
OK, then we don't know the answer. It's more a generic github question.

**Reply by davidjgraph** [reply]
```
curl -sL https://github.com/jgraph/drawio-desktop/releases/latest/download/latest-linux.yml -o /tmp/latest-linux.yml
VERSION=$(awk '/^version:/ {print $2}' /tmp/latest-linux.yml)
DEB_NAME=$(awk '/url: drawio-amd64.*\.deb/ {print $3}' /tmp/latest-linux.yml)
curl -sL -o /tmp/drawio.deb \
  "https://github.com/jgraph/drawio-desktop/releases/download/v${VERSION}/${DEB_NAME}"
```

**Comment by rungitringit** [comment]
> OK, then we don't know the answer. It's more a generic github question.

Thanks David.  Is there any way you are able to apply a tag to the latest release and remove it from the last release each time you do a release?

I hacked together this work-around script for now, but it is fragile as any change to the download paths, or your version numbering would break it.  (EDIT: Someone more confident with regex could probably improve it)

```
#!/bin/bash
# Potentially fragile script to ensure draw.io electron app is up to date.
# Run from cron once a week.

curl --silent --location --output /tmp/drawio-index.html https://github.com/jgraph/drawio-desktop/releases/latest

# Fragile, index format or filename could change.
URL=$( grep drawio-amd64 /tmp/drawio-index.html | cut -d\" -f2 )

# Fragile, URL could change in future.
SRC_VER=$( echo "${URL}" | cut -d'v' -f2 | cut -d'/' -f1 )

if dpkg-query --show --showformat='${Status}' draw.io | grep --silent ' install'
then
    CUR_VER=$( dpkg-query --show --showformat='${Version}' draw.io )
    if dpkg --compare-versions "${CUR_VER}" "ge" "${SRC_VER}"
    then
        # Current installed version is newer or the same, cleanup and exit
        rm /tmp/drawio-index.html
        exit 0
    fi
fi

curl --silent --location --output /tmp/drawio-x86_64-latest.deb "${URL}"
sudo apt-get install --quiet -y /tmp/drawio-x86_64-latest.deb && rm /tmp/drawio-x86_64-latest.deb
rm /tmp/drawio-index.html
```

**Comment by svarrette-anssi** [comment]
In complement, and sorry if it's naive, but I wonder how the `sha512` field of the `latest-linux.yml` is encoded such that it can be used to verify the checkum of the download file (I'm trying to automate it in my ansible playbook). 

Ex for the .deb package : 
```bash 
$ sha512sum /tmp/drawio-amd64-29.3.0.deb 
2e2d3b98891ade20741e6be4384bdf77b76484356c7e839ff6dd305a242e83699f02654269e1293baaa144db46de61f697d5be35f99ecb5bcaa3ea1c11fcfca1  /tmp/drawio-amd64-29.3.0.deb

# some trials to check what could have been used... 
$ openssl passwd -6 $(sha512sum /tmp/drawio-amd64-29.3.0.deb | awk '{print $1}')
$6$rzKnbX8OzL5FQjWf$WS7A45dMEuS51FPr4EkVfRx9vwq9kPl.obOjQgoyVhxtMNw2e612ui88t6O7lTJxxuv7P8jELLF0XeGSOqvCO0
$ sha512sum /tmp/drawio-amd64-29.3.0.deb | awk '{print $1}' | base64
MmUyZDNiOTg4OTFhZGUyMDc0MWU2YmU0Mzg0YmRmNzdiNzY0ODQzNTZjN2U4MzlmZjZkZDMwNWEy
NDJlODM2OTlmMDI2NTQyNjllMTI5M2JhYWExNDRkYjQ2ZGU2MWY2OTdkNWJlMzVmOTllY2I1YmNh
YTNlYTFjMTFmY2ZjYTEK
```

when the manifest file proposes: 

```yaml
# latest-linux.yml
version: 29.3.0
files:
  - url: drawio-x86_64-29.3.0.AppImage
    sha512: m9jWx5myc+Xf00SUH+Mh+i9lI+8rvqg71wNhS/j98/aDEbNXf3T+tREjUQ0aoT9UI+x0Gl3IU56omCcb0ClXGg==
    size: 150957131
    blockMapSize: 158815
  - url: drawio-amd64-29.3.0.deb
    sha512: Li07mIka3iB0HmvkOEvfd7dkhDVsfoOf9t0wWiQug2mfAmVCaeEpO6qhRNtG3mH2l9W+Nfmey1vKo+ocEfz8oQ==
    size: 120171688
  - url: drawio-x86_64-29.3.0.rpm
    sha512: knfepqjiGITGPmpv8Nz28TkNvxCTnDTO3AZbuzjF/ykV5YVJm6E+2k4k7m4T6dGwCzodee9R1XlHkEKHSt1l1A==
    size: 105561845
path: drawio-x86_64-29.3.0.AppImage
sha512: m9jWx5myc+Xf00SUH+Mh+i9lI+8rvqg71wNhS/j98/aDEbNXf3T+tREjUQ0aoT9UI+x0Gl3IU56omCcb0ClXGg==
releaseDate: '2026-01-08T23:39:02.267Z'
```
