### ISSUE TITLE
Cheksum and Update Problem

### ISSUE THREAD

**Issue by hlldz** [jgraph/drawio-desktop#729]
Hi,

Yesterday I was getting a checksum mismatch error while updating to version 15.3.7.
<img width="1014" alt="drw" src="https://user-images.githubusercontent.com/16455559/135406821-c5602a3a-886a-45ce-bd83-6fa4c3064d90.png">

Today, I cannot upgrade to the latest release, 15.3.8 I get the warning that there is a new version, I approve it to install, but it does not install. I'm not getting any errors either. Every time I open the application, I get the same warning that there is a new version.

```
openssl dgst -sha512 -binary draw.io-x64-15.3.8.dmg | openssl enc -base64
EvVqNO70DKoInnHOy7ggJpOd6JCcwWIGauJTaLWSL2T4YziY32AiEaMuynRQWkv7RywgiWECrFDSpTuLg7CkOg==
```

```
latest-mac.yml Content:

version: 15.3.8
files:
  - url: draw.io-x64-15.3.8.zip
    sha512: vifKAgWjbHs/97nSb/pWUBq0jclbUmfVcrK9MvOlOt8YrKlAfvJcLRWsCgrnjgxNHkNU4CBfhVcUwnmSkCZmIA==
    size: 116905326
    blockMapSize: 121564
  - url: draw.io-arm64-15.3.8.zip
    sha512: 64lHQCYAfb8X9t2v7hzl52qj6AW27HNtmjZJzvh1qoxI/yqH8yG8qOnNnyUfqbPKH2TcuARc47OuFWoRZs+BGw==
    size: 118576562
    blockMapSize: 124458
  - url: draw.io-x64-15.3.8.dmg
    sha512: MZUaxkJV2modDKRdnIiDeVpdjhXdVcIk4mMc8dgPQQ5sjJSz8ZPw6VCAoA2sqqr6MOB/Cm8nHA9JiEkvj9qxpQ==
    size: 120589831
  - url: draw.io-arm64-15.3.8.dmg
    sha512: bcdSIoY7j0POjD0GpBkdJNHhjmdQtlC7P/b84zcdBM2kySumq9WXasFzwdYR7NCNT2QneesfTLSKDkcysf39NA==
    size: 122539884
path: draw.io-x64-15.3.8.zip
sha512: vifKAgWjbHs/97nSb/pWUBq0jclbUmfVcrK9MvOlOt8YrKlAfvJcLRWsCgrnjgxNHkNU4CBfhVcUwnmSkCZmIA==
releaseDate: '2021-09-29T11:23:37.133Z'

```

Current Draw.io Version & OS => 15.2.7 & Mac OS X
